function g3 = load_plate(x,y)
%LOAD_PLATE
%    G3 = LOAD_PLATE(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    10-Nov-2017 15:18:29

t2 = x-1.0;
t3 = x.^2;
t4 = y-1.0;
t5 = y.^2;
t6 = t5.*5.0;
t7 = t6-y.*5.0+1.0;
t8 = t3.*5.0;
t9 = t8-x.*5.0+1.0;
g3 = t2.*t7.*x.*(t2.^2.*t3.*2.0+t4.*t9.*y).*1.2e7+t4.*t9.*y.*(t4.^2.*t5.*2.0+t2.*t7.*x).*1.2e7;
