function theta1y = theta1_y(x,y)
%THETA1_Y
%    THETA1Y = THETA1_Y(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    28-Oct-2017 12:18:55

t2 = x-1.0;
t3 = y-1.0;
t4 = t3.^2;
t5 = x.^2;
t6 = y.^2;
t7 = x.*2.0;
t8 = t7-1.0;
t9 = t2.^2;
theta1y = t3.*t4.*t5.*t6.*t8.*t9.*3.0+t4.*t5.*t6.*t8.*t9.*y.*3.0;
