function theta1 = theta1(x,y)
%THETA1
%    THETA1 = THETA1(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    28-Oct-2017 12:18:54

t2 = y.^2;
t3 = x-1.0;
t4 = y-1.0;
t5 = t4.^2;
theta1 = t2.*t3.^2.*t4.*t5.*x.^2.*y.*(x.*2.0-1.0);
