function theta2y = theta2_y(x,y)
%THETA2_Y
%    THETA2Y = THETA2_Y(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    10-Nov-2017 11:01:37

t2 = x.^2;
t3 = x-1.0;
t4 = t3.^2;
t5 = y-1.0;
t6 = t5.^2;
t7 = y.^2;
t8 = y.*2.0;
t9 = t8-1.0;
theta2y = t2.*t3.*t4.*t6.*t7.*x.*2.0+t2.*t3.*t4.*t6.*t9.*x.*y.*2.0+t2.*t3.*t4.*t7.*t9.*x.*(t8-2.0);
