function theta2 = theta2(x,y)
%THETA2
%    THETA2 = THETA2(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    28-Oct-2017 12:18:55

t2 = x.^2;
t3 = x-1.0;
t4 = t3.^2;
t5 = y-1.0;
theta2 = t2.*t3.*t4.*t5.^2.*x.*y.^2.*(y.*2.0-1.0);
