function w = w(x,y)
%W
%    W = W(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    28-Oct-2017 12:18:55

t2 = x.^2;
t3 = y.^2;
t4 = x-1.0;
t5 = t4.^2;
t6 = y-1.0;
t7 = t6.^2;
t8 = t3-1.0;
t9 = t8.^2;
w = t2.*t3.*t4.*t5.*t6.*t7.*x.*y.*(1.0./3.0)-t2.^2.*t3.^2.*t5.^2.*t6.*t8.*t9.*(t2.*5.0-x.*5.0+1.0).*(t3.*5.0-y.*5.0+1.0).*(1.0./1.875e4);
