function w = w(x,y)
%W
%    W = W(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    10-Nov-2017 11:01:37

t2 = x.^2;
t3 = y.^2;
t4 = x-1.0;
t5 = t4.^2;
t6 = y-1.0;
t7 = t6.^2;
w = t3.*t4.*t6.*t7.*x.*y.*(t2.*5.0-x.*5.0+1.0).*(-1.0./1.875e4)-t2.*t4.*t5.*t6.*x.*y.*(t3.*5.0-y.*5.0+1.0).*(1.0./1.875e4)+t2.*t3.*t4.*t5.*t6.*t7.*x.*y.*(1.0./3.0);
